output proper exit code when no changes are required

diff --git a/.github/workflows/test_and_deploy.yaml b/.github/workflows/test_and_deploy.yaml
--- a/.github/workflows/test_and_deploy.yaml
+++ b/.github/workflows/test_and_deploy.yaml
@@ -1,8 +1,8 @@
 name: Test and Deploy CloudFormation Templates
 on:
   push:
-    # paths:
-    #   - 'deployments/*'
+    paths:
+      - 'deployments/*'
 permissions:
       id-token: write
       contents: write
@@ -89,7 +89,12 @@ jobs:
           ASSUMED_ROLE_NAME: ${{ needs.SetConfigVariables.outputs.assumed_role_name }}
       - name: Policy as Code Validation
         if: needs.SetConfigVariables.outputs.policy_as_code_provider != 'None'
-        run: python -m scripts.deploy --branch ${{ github.ref_name }} --account_number ${{ needs.SetConfigVariables.outputs.branch_type == 'major' && secrets[env.SECRET_NAME] || '123456789012' }} --job validate
+        run: |
+          RESULT=$(python -m scripts.deploy --branch ${{ github.ref_name }} --account_number ${{ needs.SetConfigVariables.outputs.branch_type == 'major' && secrets[env.SECRET_NAME] || '123456789012' }} --job validate)
+          if [ $RESULT -ne 0 ]; then
+            echo "ERROR: See logs for details."
+            exit $RESULT
+          fi
   Deploy:
     runs-on: ubuntu-latest
     needs: [SetConfigVariables, Test]
