Test updated deployment to prod (#10)
* updated how code handles missing parameter file for policy as code validation

* first cut of github workflow

* Add script to setup GitHub Actions environment variables from config

* Tested cfn-guard and OPA installation process

* first e2e lint test

* set 'e2e-test' branch to minor

* test OPA placeholder method call

* add OPA to config settings

* add default values when validating minor branches

* added missing default value

* test deliberate cfn-guard failure

* Set minor branches to use config from lowest environment

* create rendered templates in tmp folder on runner

* added constraint on assuming role on minor branches

* edit rendered template path

* use github home directory for rendered templates

* added error handling for lack of AWS credentials on minor branches

* use environment variable to get home directory

* Test if directory exists on github runner

* log folder creation attempt

* Folder existence 2nd attempt

* change write mode

* update folder permissions

* unsecure test

* fix handling of NoCredentialsError

* loosen directory restrictions

* adjust cfn-guard PATH setting

* source bashrc after adding cfn-guard to PATH

* uncomment linting steps

* call guard directly from bin

* confirm installation location

* get contents of bin

* another attempt to directly call guard

* expand ~

* dynamically configure guard command location

* fixed typo

* Test validation corrections

* Attempt cfn-guard installation via Homebrew while guard team fixes bash script

* update sub handling of AWS::Partition

* updated handling of pseudo-parameters in Sub function references

* test calling cfn-guard from Homebrew installation

* test where homebrew installs cfn-guard

* check /usr folder

* check local folder

* use brew info command to get data

* test ternary cfn-guard installation

* Ternary again with Homebrew

* test new brew syntax

* Revert cfn-guard installation method and re-attempt validation fixes

* revert cfn-guard command call

* fix another guard typo

* streamline rendered template path

* attempt a purposeful guard failure

* debug incorrect validation result

* revert to adding rendered templates individually

* attempt deployment test without validation

* trigger deployment test to dev environment

* remove deployment restriction

* add missing deployment dependencies

* add boto3

* add missing environment variable

* grant github action ability to update repo tagging

* Rename export to avoid conflict in prod

* clean up duplicate from merge conflict

* add exit code for aborted operation

* ensure process checks remote for deployment tag if missing locally

* fetch tags rather than pulling

* Updated logic to skip validation and deployment attempts if there are no changes in templates

* fetch tags rather than pulling

* Updated logic to skip validation and deployment attempts if there are no changes in templates

* output proper exit code when no changes are required

* Purposely fail linting

* return exit code of deployment script and fail pipeline if necessary

* return deployment exit code to pipeline

* test deletion process

* delete rather than rename file

* re-add example.json

* Updated pytest inpute parameters in preparation for config validation workflow

* fixed logic to identify deleted templates

* enable restriction on workflow trigger

* trigger dev deployment

* test template deletion process

* Add fixes to handle template deletions (#9)

* remove template validation as it is already accomplished in lint stage

* set size to 0 if file does not exist

* add .jsn as valid file suffix

* trigger dev pipeline

diff --git a/.github/workflows/test_and_deploy.yaml b/.github/workflows/test_and_deploy.yaml
--- a/.github/workflows/test_and_deploy.yaml
+++ b/.github/workflows/test_and_deploy.yaml
@@ -1,8 +1,8 @@
 name: Test and Deploy CloudFormation Templates
 on:
   push:
-    # paths:
-    #   - 'deployments/*'
+    paths:
+      - 'deployments/**'
 permissions:
       id-token: write
       contents: write
@@ -115,4 +115,9 @@ jobs:
       - name: Deploy Templates
         env:
           SECRET_NAME: ${{ needs.SetConfigVariables.outputs.account_secret_name }}
-        run: python -m scripts.deploy --branch ${{ github.ref_name }} --account_number ${{ secrets[env.SECRET_NAME] }} --job deploy
+        run: |
+          RESULT=$(python -m scripts.deploy --branch ${{ github.ref_name }} --account_number ${{ secrets[env.SECRET_NAME] }} --job deploy)
+          if [ $RESULT -ne 0 ]; then
+            echo "ERROR: See logs for details."
+            exit $RESULT
+          fi
